### ISSUE TITLE
identify top essential categories

### ISSUE THREAD

**Issue by abhinavdalal** [svs/covid19-supply-chain#3]

**Comment by svs** [comment]
- Essentials
  - Food
    - Flour
       - Atta
       - Besan
       - Maida
    - Bread
    - Rice
    - Pulses
      - Daal
      - Rajma / Chhole
    - Staples
      - Salt
      - Sugar
      - Oil
      - Spices
    - Dairy
      - Milk
      - Dahi
      - Butter
      - Cheese
    - Breakfast Foods
      - Eggs
      - Poha/Suji
    - Beverages
       - Tea
       - Coffee
       - Soft Drinks
    - Vegetables
      - Staples 
         - Onions
         - Potatoes 
   - Meats
     - Chicken
     - Mutton
     - Fish
